# Generated by Django 4.2.1 on 2023-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('purchase', models.CharField(max_length=10)),
                ('sale', models.CharField(max_length=10)),
                ('qty', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('U', 'U')], max_length=1, null=True)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
